apiVersion: v1
kind: ServiceAccount
metadata:
  name: ref-ksa-v3
  namespace: referrals-ns-v3
  annotations:
    iam.gke.io/gcp-service-account: ref-gsa-v3@referrals-gcp-v3-dev.iam.gserviceaccount.com