apiVersion: v1
kind: ServiceAccount
metadata:
  name: ref-ksa-v2
  namespace: referrals-ns-v2
  annotations:
    iam.gke.io/gcp-service-account: ref-gsa-v2@project-9627b595-2a5e-4fc1-9f1.iam.gserviceaccount.com