spring.application.name=Referral-Live
server.port=8081
spring.jpa.defer-datasource-initialization=false
spring.jpa.show-sql=true

# In case of a real DB (e.g. production, SIT), do not initialize the DB i.e. keep spring.sql.init.mode=never (else always or embedded)
spring.sql.init.mode=never

# Use Real Environment/DB like PostgreSQL
# spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/postgres (SPRING_DATASOURCE_URL in Deployment.yaml)
# spring.datasource.username=referrals-app-gsa@project.iam.gserviceaccount.com  (SPRING_DATASOURCE_USERNAME in Deployment.yaml)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.sslmode=disable