apiVersion: v1
kind: Service
metadata:
  name: referrals-app-svc
  namespace: referrals-ns
  labels:
    app: referrals-app
spec:
  selector:
    app: referrals-app
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  type: ClusterIP